version: "3.8"

services:
  php:
    container_name: slim_php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/slim_app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    container_name: slim_nginx
    image: nginx:stable-alpine
    ports:
      - '${WEB_PORT:-8080}:80'
    volumes:
      - .:/var/www/slim_app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php


  database:
    container_name: mysql
    ports:
      - "${DATABASE_PORT_LOCAL:-3308}:3306"
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    cap_add:
      - SYS_NICE
>>>>>>> cb73f8c (second commit)
