version: "3.8"

services:
  php:
    container_name: slim_php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/slim_app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    container_name: slim_nginx
    image: nginx:stable-alpine
    ports:
      - '8999:80'
    volumes:
      - .:/var/www/slim_app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php